#
  
spring:
  data:
    mongodb:
      database: mydb
      uri: mongodb://yanshu:root@localhost:27017/mydb  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
  cache:
    cache-names: persons    redis:      time-to-live: 600000
      