#
  
spring:
# MongoDB Configuration
  data:
    mongodb:
      database: mydb
      uri: mongodb://yanshu:root@localhost:27017/mydb
# RabbitMQ Configuration  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
  cache:
    cache-names: persons, chache2,    redis:      time-to-live: 600000
# Spring Cloud Config Client Configuration
  profiles:
    active:
    - default
  config:    import:    - optional:configserver:http://localhost:8888/
# Eureka Client Configuration
  application:    name: practice
# Continue. Default url is 8761, if you want to change 
eureka:
  instance:
    hostname: localhost
  client:
    enabled: true    service-url:
      defaultZone: http://localhost:8761/eureka/#      defaultZone: user:password@http://localhost:8761/eureka/
    healthcheck:      enabled: true
      
server:  port: 8080
